// <auto-generated />
using System;
using HRM.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM.API.Migrations
{
    [DbContext(typeof(HrmDbContext))]
    partial class HrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRM.API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages employee relations, recruitment, and benefits",
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages IT infrastructure, software development, and technical support",
                            IsActive = true,
                            Name = "Information Technology"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handles financial planning, accounting, and budget management",
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages marketing campaigns, brand management, and customer outreach",
                            IsActive = true,
                            Name = "Marketing"
                        },
                        new
                        {
                            DepartmentId = 5,
                            CreatedDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handles customer acquisition, sales processes, and revenue generation",
                            IsActive = true,
                            Name = "Sales"
                        },
                        new
                        {
                            DepartmentId = 6,
                            CreatedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Focuses on innovation, product development, and research initiatives",
                            IsActive = true,
                            Name = "Research & Development"
                        },
                        new
                        {
                            DepartmentId = 7,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages day-to-day operations, logistics, and process optimization",
                            IsActive = false,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HRM.API.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            CreatedDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "sarah.johnson@company.com",
                            FirstName = "Sarah",
                            HireDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Johnson",
                            PhoneNumber = "+1-555-0101",
                            Salary = 75000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            CreatedDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "michael.chen@company.com",
                            FirstName = "Michael",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Chen",
                            PhoneNumber = "+1-555-0102",
                            Salary = 68000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            CreatedDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "emma.wilson@company.com",
                            FirstName = "Emma",
                            HireDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Wilson",
                            PhoneNumber = "+1-555-0201",
                            Salary = 95000m
                        },
                        new
                        {
                            EmployeeId = 4,
                            CreatedDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "david.rodriguez@company.com",
                            FirstName = "David",
                            HireDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rodriguez",
                            PhoneNumber = "+1-555-0202",
                            Salary = 88000m
                        },
                        new
                        {
                            EmployeeId = 5,
                            CreatedDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "jessica.taylor@company.com",
                            FirstName = "Jessica",
                            HireDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Taylor",
                            PhoneNumber = "+1-555-0203",
                            Salary = 72000m
                        },
                        new
                        {
                            EmployeeId = 6,
                            CreatedDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "robert.anderson@company.com",
                            FirstName = "Robert",
                            HireDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Anderson",
                            PhoneNumber = "+1-555-0301",
                            Salary = 82000m
                        },
                        new
                        {
                            EmployeeId = 7,
                            CreatedDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "lisa.martinez@company.com",
                            FirstName = "Lisa",
                            HireDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Martinez",
                            PhoneNumber = "+1-555-0302",
                            Salary = 71000m
                        },
                        new
                        {
                            EmployeeId = 8,
                            CreatedDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 4,
                            Email = "amanda.thompson@company.com",
                            FirstName = "Amanda",
                            HireDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Thompson",
                            PhoneNumber = "+1-555-0401",
                            Salary = 65000m
                        },
                        new
                        {
                            EmployeeId = 9,
                            CreatedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 4,
                            Email = "james.brown@company.com",
                            FirstName = "James",
                            HireDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Brown",
                            PhoneNumber = "+1-555-0402",
                            Salary = 58000m
                        },
                        new
                        {
                            EmployeeId = 10,
                            CreatedDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 5,
                            Email = "kevin.davis@company.com",
                            FirstName = "Kevin",
                            HireDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Davis",
                            PhoneNumber = "+1-555-0501",
                            Salary = 70000m
                        },
                        new
                        {
                            EmployeeId = 11,
                            CreatedDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 5,
                            Email = "rachel.miller@company.com",
                            FirstName = "Rachel",
                            HireDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Miller",
                            PhoneNumber = "+1-555-0502",
                            Salary = 63000m
                        },
                        new
                        {
                            EmployeeId = 12,
                            CreatedDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 6,
                            Email = "alan.kumar@company.com",
                            FirstName = "Dr. Alan",
                            HireDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kumar",
                            PhoneNumber = "+1-555-0601",
                            Salary = 105000m
                        });
                });

            modelBuilder.Entity("HRM.API.Models.Employee", b =>
                {
                    b.HasOne("HRM.API.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRM.API.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
